apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ Release.Name }}-grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.datasources.prometheus | quote }}
        isDefault: true
