apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ Release.Name }}-grafana
  labels:
    app: {{ Release.Name }}-grafana
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: {{ Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ Release.Name }}-grafana
    spec:
      containers:
        - name: {{ Release.Name }}-grafana
          image: grafana/grafana:9.4.7
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"  # Default admin password, can be overridden by secret
              # valueFrom:
              #   secretKeyRef:
              #     name: grafana-admin-password
              #     key: password
            - name: GF_DASHBOARDS_JSON_ENABLED
              value: "true"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: datasources
          configMap:
            name: {{ Release.Name }}-grafana-datasources
