apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.grafana.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.grafana.ingress.host }}
    traefik.ingress.kubernetes.io/router.entrypoints: {{ ternary "websecure" "web" .Values.grafana.ingress.tls.enabled }}
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.grafana.ingress.tls.clusterIssuer }}
    {{- end }}
spec:
  {{- if .Values.grafana.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.grafana.ingress.host }}
      secretName: grafana-tls
  {{- end }}
  rules:
    - host: {{ .Values.grafana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: {{ .Values.grafana.service.port }}