apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}-jaeger-query
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.jaeger.name }}-jaeger-query
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
    - port: {{ .Values.jaeger.service.port }}
      targetPort: 16686
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.jaeger.name }}-jaeger-query
