apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}-jaeger-query
spec:
  selector:
    app: {{ .Values.jaeger.name }}-jaeger-query
  ports:
    - name: http
      port: 80
      targetPort: 16686