apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otel.name }}-otel
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.otel.name }}-otel
spec:
  replicas: {{ .Values.otel.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.otel.name }}-otel
  template:
    metadata:
      labels:
        app: {{ .Values.otel.name }}-otel
    spec:
      containers:
        - name: {{ .Values.otel.name }}-otel
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config", "/etc/otel/otel-collector-config.yaml"]
          env:
            - name: ES_ENDPOINT
              value: {{ .Values.otel.elasticsearch.endpoint }}
            - name: ES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.otel.elasticsearch.secretName }}
                  key: apiKey
            - name: NEW_RELIC_OTLP_ENDPOINT
              value: {{ .Values.otel.newRelic.endpoint }}
            - name: NEW_RELIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.otel.newRelic.secretName }}
                  key: apiKey
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.otel.dataDog.secretName }}
                  key: apiKey
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 13133
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel
              readOnly: true
      volumes:
        - name: otel-collector-config
          configMap:
            name: {{ .Values.otel.name }}-otel-config