# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: {{ .Release.Name }}
#   annotations:
#   {{- toYaml .Values.service.annotations | nindent 4 }}
#   name: {{ .Release.Name }}
# spec:
#   selector:
#     app: {{ .Release.Name }}
#   {{- with .Values.service.spec }}
#     {{- toYaml . | nindent 2 }}
#   {{- end }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: { { .Release.Name } }
  name: { { .Release.Name } }
spec:
  selector:
    app: { { .Release.Name } }
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
