{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.blueGreen.activeService }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.blueGreen.previewService }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP

{{- else }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP

{{- end }}